/**
 * Plant Library - Local plant data for the garden planner
 * Names in French with Latin name in parentheses
 */

export type PlantCategory =
  | 'tree'
  | 'fruit_tree'
  | 'shrub'
  | 'perennial'
  | 'hedge'
  | 'annual'
  | 'vegetable'
  | 'herb'
  | 'berry'
  | 'wall_plant'
  | 'bulb';

export interface GrowthModel {
  species: string;
  common_name: string;
  mature_height_cm: number;
  mature_canopy_cm: number;
  growth_rate: 'slow' | 'medium' | 'fast';
  years_to_mature: number;
  carbon_per_year_kg: number;
}

export const PLANT_LIBRARY: Record<PlantCategory, GrowthModel[]> = {
  tree: [
    {
      species: 'quercus_robur',
      common_name: 'Chêne pédonculé (Quercus robur)',
      mature_height_cm: 2500,
      mature_canopy_cm: 2000,
      growth_rate: 'slow',
      years_to_mature: 50,
      carbon_per_year_kg: 22,
    },
    {
      species: 'fagus_sylvatica',
      common_name: 'Hêtre commun (Fagus sylvatica)',
      mature_height_cm: 3000,
      mature_canopy_cm: 1500,
      growth_rate: 'medium',
      years_to_mature: 40,
      carbon_per_year_kg: 18,
    },
    {
      species: 'betula_pendula',
      common_name: 'Bouleau verruqueux (Betula pendula)',
      mature_height_cm: 2000,
      mature_canopy_cm: 1000,
      growth_rate: 'fast',
      years_to_mature: 20,
      carbon_per_year_kg: 12,
    },
    {
      species: 'acer_campestre',
      common_name: 'Érable champêtre (Acer campestre)',
      mature_height_cm: 1500,
      mature_canopy_cm: 1200,
      growth_rate: 'medium',
      years_to_mature: 30,
      carbon_per_year_kg: 10,
    },
    {
      species: 'tilia_cordata',
      common_name: 'Tilleul à petites feuilles (Tilia cordata)',
      mature_height_cm: 2500,
      mature_canopy_cm: 1500,
      growth_rate: 'medium',
      years_to_mature: 40,
      carbon_per_year_kg: 16,
    },
    {
      species: 'sorbus_aucuparia',
      common_name: 'Sorbier des oiseleurs (Sorbus aucuparia)',
      mature_height_cm: 1200,
      mature_canopy_cm: 800,
      growth_rate: 'medium',
      years_to_mature: 15,
      carbon_per_year_kg: 8,
    },
    {
      species: 'fraxinus_excelsior',
      common_name: 'Frêne commun (Fraxinus excelsior)',
      mature_height_cm: 3000,
      mature_canopy_cm: 2000,
      growth_rate: 'fast',
      years_to_mature: 30,
      carbon_per_year_kg: 20,
    },
    {
      species: 'salix_alba',
      common_name: 'Saule blanc (Salix alba)',
      mature_height_cm: 2500,
      mature_canopy_cm: 1500,
      growth_rate: 'fast',
      years_to_mature: 15,
      carbon_per_year_kg: 14,
    },
  ],
  fruit_tree: [
    {
      species: 'malus_domestica',
      common_name: 'Pommier (Malus domestica)',
      mature_height_cm: 400,
      mature_canopy_cm: 400,
      growth_rate: 'medium',
      years_to_mature: 8,
      carbon_per_year_kg: 5,
    },
    {
      species: 'prunus_avium',
      common_name: 'Cerisier sauvage (Prunus avium)',
      mature_height_cm: 1500,
      mature_canopy_cm: 1000,
      growth_rate: 'medium',
      years_to_mature: 10,
      carbon_per_year_kg: 10,
    },
    {
      species: 'prunus_cerasus',
      common_name: 'Griottier (Prunus cerasus)',
      mature_height_cm: 400,
      mature_canopy_cm: 400,
      growth_rate: 'medium',
      years_to_mature: 5,
      carbon_per_year_kg: 4,
    },
    {
      species: 'pyrus_communis',
      common_name: 'Poirier (Pyrus communis)',
      mature_height_cm: 500,
      mature_canopy_cm: 350,
      growth_rate: 'medium',
      years_to_mature: 8,
      carbon_per_year_kg: 5,
    },
    {
      species: 'prunus_domestica',
      common_name: 'Prunier (Prunus domestica)',
      mature_height_cm: 400,
      mature_canopy_cm: 400,
      growth_rate: 'medium',
      years_to_mature: 6,
      carbon_per_year_kg: 4,
    },
    {
      species: 'prunus_domestica_mirabelle',
      common_name: 'Mirabellier (Prunus domestica)',
      mature_height_cm: 500,
      mature_canopy_cm: 450,
      growth_rate: 'medium',
      years_to_mature: 6,
      carbon_per_year_kg: 4,
    },
    {
      species: 'juglans_regia',
      common_name: 'Noyer commun (Juglans regia)',
      mature_height_cm: 2500,
      mature_canopy_cm: 1500,
      growth_rate: 'slow',
      years_to_mature: 20,
      carbon_per_year_kg: 15,
    },
    {
      species: 'castanea_sativa',
      common_name: 'Châtaignier (Castanea sativa)',
      mature_height_cm: 2000,
      mature_canopy_cm: 1500,
      growth_rate: 'medium',
      years_to_mature: 25,
      carbon_per_year_kg: 12,
    },
  ],
  shrub: [
    {
      species: 'cornus_sanguinea',
      common_name: 'Cornouiller sanguin (Cornus sanguinea)',
      mature_height_cm: 300,
      mature_canopy_cm: 300,
      growth_rate: 'medium',
      years_to_mature: 5,
      carbon_per_year_kg: 2,
    },
    {
      species: 'viburnum_opulus',
      common_name: 'Viorne obier (Viburnum opulus)',
      mature_height_cm: 400,
      mature_canopy_cm: 350,
      growth_rate: 'medium',
      years_to_mature: 6,
      carbon_per_year_kg: 2.5,
    },
    {
      species: 'sambucus_nigra',
      common_name: 'Sureau noir (Sambucus nigra)',
      mature_height_cm: 600,
      mature_canopy_cm: 500,
      growth_rate: 'fast',
      years_to_mature: 5,
      carbon_per_year_kg: 3,
    },
    {
      species: 'hydrangea_macrophylla',
      common_name: 'Hortensia (Hydrangea macrophylla)',
      mature_height_cm: 200,
      mature_canopy_cm: 200,
      growth_rate: 'medium',
      years_to_mature: 4,
      carbon_per_year_kg: 1,
    },
    {
      species: 'corylus_avellana',
      common_name: 'Noisetier (Corylus avellana)',
      mature_height_cm: 500,
      mature_canopy_cm: 400,
      growth_rate: 'medium',
      years_to_mature: 8,
      carbon_per_year_kg: 3,
    },
    {
      species: 'crataegus_monogyna',
      common_name: 'Aubépine (Crataegus monogyna)',
      mature_height_cm: 800,
      mature_canopy_cm: 600,
      growth_rate: 'medium',
      years_to_mature: 15,
      carbon_per_year_kg: 4,
    },
    {
      species: 'rosa_canina',
      common_name: 'Églantier (Rosa canina)',
      mature_height_cm: 300,
      mature_canopy_cm: 300,
      growth_rate: 'medium',
      years_to_mature: 4,
      carbon_per_year_kg: 1.5,
    },
    {
      species: 'prunus_spinosa',
      common_name: 'Prunellier (Prunus spinosa)',
      mature_height_cm: 400,
      mature_canopy_cm: 350,
      growth_rate: 'medium',
      years_to_mature: 8,
      carbon_per_year_kg: 2.5,
    },
    {
      species: 'syringa_vulgaris',
      common_name: 'Lilas commun (Syringa vulgaris)',
      mature_height_cm: 400,
      mature_canopy_cm: 300,
      growth_rate: 'medium',
      years_to_mature: 6,
      carbon_per_year_kg: 2,
    },
    {
      species: 'buddleja_davidii',
      common_name: 'Arbre aux papillons (Buddleja davidii)',
      mature_height_cm: 300,
      mature_canopy_cm: 250,
      growth_rate: 'fast',
      years_to_mature: 3,
      carbon_per_year_kg: 1.5,
    },
  ],
  perennial: [
    {
      species: 'lavandula_angustifolia',
      common_name: 'Lavande vraie (Lavandula angustifolia)',
      mature_height_cm: 60,
      mature_canopy_cm: 60,
      growth_rate: 'medium',
      years_to_mature: 2,
      carbon_per_year_kg: 0.3,
    },
    {
      species: 'echinacea_purpurea',
      common_name: 'Échinacée pourpre (Echinacea purpurea)',
      mature_height_cm: 120,
      mature_canopy_cm: 60,
      growth_rate: 'medium',
      years_to_mature: 2,
      carbon_per_year_kg: 0.2,
    },
    {
      species: 'rudbeckia_fulgida',
      common_name: 'Rudbeckie brillante (Rudbeckia fulgida)',
      mature_height_cm: 90,
      mature_canopy_cm: 60,
      growth_rate: 'fast',
      years_to_mature: 1,
      carbon_per_year_kg: 0.2,
    },
    {
      species: 'hosta_sieboldiana',
      common_name: 'Hosta (Hosta sieboldiana)',
      mature_height_cm: 60,
      mature_canopy_cm: 90,
      growth_rate: 'slow',
      years_to_mature: 4,
      carbon_per_year_kg: 0.3,
    },
    {
      species: 'geranium_pratense',
      common_name: 'Géranium des prés (Geranium pratense)',
      mature_height_cm: 75,
      mature_canopy_cm: 60,
      growth_rate: 'medium',
      years_to_mature: 2,
      carbon_per_year_kg: 0.2,
    },
    {
      species: 'digitalis_purpurea',
      common_name: 'Digitale pourpre (Digitalis purpurea)',
      mature_height_cm: 150,
      mature_canopy_cm: 50,
      growth_rate: 'fast',
      years_to_mature: 2,
      carbon_per_year_kg: 0.3,
    },
    {
      species: 'salvia_nemorosa',
      common_name: 'Sauge des bois (Salvia nemorosa)',
      mature_height_cm: 60,
      mature_canopy_cm: 45,
      growth_rate: 'medium',
      years_to_mature: 2,
      carbon_per_year_kg: 0.2,
    },
    {
      species: 'sedum_spectabile',
      common_name: 'Orpin d\'automne (Sedum spectabile)',
      mature_height_cm: 50,
      mature_canopy_cm: 50,
      growth_rate: 'medium',
      years_to_mature: 2,
      carbon_per_year_kg: 0.2,
    },
    {
      species: 'knautia_arvensis',
      common_name: 'Knautie des champs (Knautia arvensis)',
      mature_height_cm: 100,
      mature_canopy_cm: 40,
      growth_rate: 'medium',
      years_to_mature: 2,
      carbon_per_year_kg: 0.15,
    },
    {
      species: 'leucanthemum_vulgare',
      common_name: 'Marguerite (Leucanthemum vulgare)',
      mature_height_cm: 70,
      mature_canopy_cm: 40,
      growth_rate: 'fast',
      years_to_mature: 1,
      carbon_per_year_kg: 0.1,
    },
    {
      species: 'alchemilla_mollis',
      common_name: 'Alchémille (Alchemilla mollis)',
      mature_height_cm: 50,
      mature_canopy_cm: 60,
      growth_rate: 'medium',
      years_to_mature: 2,
      carbon_per_year_kg: 0.2,
    },
    {
      species: 'nepeta_cataria',
      common_name: 'Herbe à chat (Nepeta cataria)',
      mature_height_cm: 60,
      mature_canopy_cm: 60,
      growth_rate: 'fast',
      years_to_mature: 1,
      carbon_per_year_kg: 0.15,
    },
  ],
  hedge: [
    {
      species: 'carpinus_betulus',
      common_name: 'Charme commun (Carpinus betulus)',
      mature_height_cm: 400,
      mature_canopy_cm: 100,
      growth_rate: 'medium',
      years_to_mature: 10,
      carbon_per_year_kg: 3,
    },
    {
      species: 'taxus_baccata',
      common_name: 'If commun (Taxus baccata)',
      mature_height_cm: 300,
      mature_canopy_cm: 80,
      growth_rate: 'slow',
      years_to_mature: 15,
      carbon_per_year_kg: 2,
    },
    {
      species: 'buxus_sempervirens',
      common_name: 'Buis commun (Buxus sempervirens)',
      mature_height_cm: 150,
      mature_canopy_cm: 60,
      growth_rate: 'slow',
      years_to_mature: 10,
      carbon_per_year_kg: 1,
    },
    {
      species: 'ligustrum_vulgare',
      common_name: 'Troène commun (Ligustrum vulgare)',
      mature_height_cm: 300,
      mature_canopy_cm: 80,
      growth_rate: 'fast',
      years_to_mature: 5,
      carbon_per_year_kg: 2,
    },
  ],
  annual: [
    {
      species: 'helianthus_annuus',
      common_name: 'Tournesol (Helianthus annuus)',
      mature_height_cm: 250,
      mature_canopy_cm: 60,
      growth_rate: 'fast',
      years_to_mature: 1,
      carbon_per_year_kg: 0.5,
    },
    {
      species: 'zinnia_elegans',
      common_name: 'Zinnia élégant (Zinnia elegans)',
      mature_height_cm: 90,
      mature_canopy_cm: 40,
      growth_rate: 'fast',
      years_to_mature: 1,
      carbon_per_year_kg: 0.1,
    },
    {
      species: 'cosmos_bipinnatus',
      common_name: 'Cosmos (Cosmos bipinnatus)',
      mature_height_cm: 120,
      mature_canopy_cm: 60,
      growth_rate: 'fast',
      years_to_mature: 1,
      carbon_per_year_kg: 0.1,
    },
  ],
  vegetable: [
    {
      species: 'solanum_lycopersicum',
      common_name: 'Tomate (Solanum lycopersicum)',
      mature_height_cm: 150,
      mature_canopy_cm: 60,
      growth_rate: 'fast',
      years_to_mature: 1,
      carbon_per_year_kg: 0.2,
    },
    {
      species: 'cucumis_sativus',
      common_name: 'Concombre (Cucumis sativus)',
      mature_height_cm: 200,
      mature_canopy_cm: 80,
      growth_rate: 'fast',
      years_to_mature: 1,
      carbon_per_year_kg: 0.1,
    },
    {
      species: 'brassica_oleracea',
      common_name: 'Chou (Brassica oleracea)',
      mature_height_cm: 60,
      mature_canopy_cm: 60,
      growth_rate: 'medium',
      years_to_mature: 1,
      carbon_per_year_kg: 0.2,
    },
    {
      species: 'daucus_carota',
      common_name: 'Carotte (Daucus carota)',
      mature_height_cm: 40,
      mature_canopy_cm: 30,
      growth_rate: 'medium',
      years_to_mature: 1,
      carbon_per_year_kg: 0.1,
    },
  ],
  herb: [
    {
      species: 'rosmarinus_officinalis',
      common_name: 'Romarin (Rosmarinus officinalis)',
      mature_height_cm: 100,
      mature_canopy_cm: 80,
      growth_rate: 'medium',
      years_to_mature: 3,
      carbon_per_year_kg: 0.3,
    },
    {
      species: 'thymus_vulgaris',
      common_name: 'Thym commun (Thymus vulgaris)',
      mature_height_cm: 30,
      mature_canopy_cm: 40,
      growth_rate: 'medium',
      years_to_mature: 2,
      carbon_per_year_kg: 0.1,
    },
    {
      species: 'mentha_spicata',
      common_name: 'Menthe verte (Mentha spicata)',
      mature_height_cm: 60,
      mature_canopy_cm: 60,
      growth_rate: 'fast',
      years_to_mature: 1,
      carbon_per_year_kg: 0.1,
    },
    {
      species: 'ocimum_basilicum',
      common_name: 'Basilic (Ocimum basilicum)',
      mature_height_cm: 60,
      mature_canopy_cm: 40,
      growth_rate: 'fast',
      years_to_mature: 1,
      carbon_per_year_kg: 0.1,
    },
  ],
  berry: [
    {
      species: 'rubus_idaeus',
      common_name: 'Framboisier (Rubus idaeus)',
      mature_height_cm: 180,
      mature_canopy_cm: 100,
      growth_rate: 'fast',
      years_to_mature: 2,
      carbon_per_year_kg: 0.5,
    },
    {
      species: 'ribes_nigrum',
      common_name: 'Cassissier (Ribes nigrum)',
      mature_height_cm: 150,
      mature_canopy_cm: 150,
      growth_rate: 'medium',
      years_to_mature: 3,
      carbon_per_year_kg: 0.8,
    },
    {
      species: 'ribes_rubrum',
      common_name: 'Groseillier rouge (Ribes rubrum)',
      mature_height_cm: 150,
      mature_canopy_cm: 120,
      growth_rate: 'medium',
      years_to_mature: 3,
      carbon_per_year_kg: 0.7,
    },
    {
      species: 'ribes_uva_crispa',
      common_name: 'Groseillier à maquereau (Ribes uva-crispa)',
      mature_height_cm: 120,
      mature_canopy_cm: 120,
      growth_rate: 'medium',
      years_to_mature: 3,
      carbon_per_year_kg: 0.6,
    },
    {
      species: 'vaccinium_corymbosum',
      common_name: 'Myrtillier (Vaccinium corymbosum)',
      mature_height_cm: 180,
      mature_canopy_cm: 120,
      growth_rate: 'slow',
      years_to_mature: 5,
      carbon_per_year_kg: 0.6,
    },
    {
      species: 'fragaria_ananassa',
      common_name: 'Fraisier (Fragaria ananassa)',
      mature_height_cm: 30,
      mature_canopy_cm: 40,
      growth_rate: 'fast',
      years_to_mature: 1,
      carbon_per_year_kg: 0.1,
    },
    {
      species: 'rubus_fruticosus',
      common_name: 'Mûrier sauvage (Rubus fruticosus)',
      mature_height_cm: 200,
      mature_canopy_cm: 150,
      growth_rate: 'fast',
      years_to_mature: 2,
      carbon_per_year_kg: 0.6,
    },
  ],
  wall_plant: [
    {
      species: 'sedum_acre',
      common_name: 'Orpin âcre (Sedum acre)',
      mature_height_cm: 10,
      mature_canopy_cm: 30,
      growth_rate: 'medium',
      years_to_mature: 1,
      carbon_per_year_kg: 0.05,
    },
    {
      species: 'sedum_album',
      common_name: 'Orpin blanc (Sedum album)',
      mature_height_cm: 15,
      mature_canopy_cm: 30,
      growth_rate: 'medium',
      years_to_mature: 1,
      carbon_per_year_kg: 0.05,
    },
    {
      species: 'sempervivum_tectorum',
      common_name: 'Joubarbe des toits (Sempervivum tectorum)',
      mature_height_cm: 15,
      mature_canopy_cm: 20,
      growth_rate: 'slow',
      years_to_mature: 2,
      carbon_per_year_kg: 0.03,
    },
    {
      species: 'thymus_serpyllum',
      common_name: 'Serpolet (Thymus serpyllum)',
      mature_height_cm: 10,
      mature_canopy_cm: 40,
      growth_rate: 'medium',
      years_to_mature: 1,
      carbon_per_year_kg: 0.05,
    },
    {
      species: 'cymbalaria_muralis',
      common_name: 'Cymbalaire des murs (Cymbalaria muralis)',
      mature_height_cm: 10,
      mature_canopy_cm: 30,
      growth_rate: 'fast',
      years_to_mature: 1,
      carbon_per_year_kg: 0.03,
    },
    {
      species: 'erigeron_karvinskianus',
      common_name: 'Vergerette de Karvinski (Erigeron karvinskianus)',
      mature_height_cm: 30,
      mature_canopy_cm: 40,
      growth_rate: 'fast',
      years_to_mature: 1,
      carbon_per_year_kg: 0.05,
    },
    {
      species: 'aubrieta_deltoidea',
      common_name: 'Aubriète (Aubrieta deltoidea)',
      mature_height_cm: 15,
      mature_canopy_cm: 50,
      growth_rate: 'medium',
      years_to_mature: 1,
      carbon_per_year_kg: 0.05,
    },
    {
      species: 'geranium_sanguineum',
      common_name: 'Géranium sanguin (Geranium sanguineum)',
      mature_height_cm: 40,
      mature_canopy_cm: 50,
      growth_rate: 'medium',
      years_to_mature: 2,
      carbon_per_year_kg: 0.1,
    },
    {
      species: 'centranthus_ruber',
      common_name: 'Valériane rouge (Centranthus ruber)',
      mature_height_cm: 80,
      mature_canopy_cm: 50,
      growth_rate: 'fast',
      years_to_mature: 1,
      carbon_per_year_kg: 0.1,
    },
    {
      species: 'euphorbia_cyparissias',
      common_name: 'Euphorbe petit-cyprès (Euphorbia cyparissias)',
      mature_height_cm: 40,
      mature_canopy_cm: 50,
      growth_rate: 'fast',
      years_to_mature: 1,
      carbon_per_year_kg: 0.1,
    },
  ],
  bulb: [
    {
      species: 'narcissus_pseudonarcissus',
      common_name: 'Jonquille (Narcissus pseudonarcissus)',
      mature_height_cm: 40,
      mature_canopy_cm: 15,
      growth_rate: 'medium',
      years_to_mature: 1,
      carbon_per_year_kg: 0.05,
    },
    {
      species: 'crocus_vernus',
      common_name: 'Crocus de printemps (Crocus vernus)',
      mature_height_cm: 15,
      mature_canopy_cm: 10,
      growth_rate: 'medium',
      years_to_mature: 1,
      carbon_per_year_kg: 0.02,
    },
    {
      species: 'galanthus_nivalis',
      common_name: 'Perce-neige (Galanthus nivalis)',
      mature_height_cm: 15,
      mature_canopy_cm: 10,
      growth_rate: 'slow',
      years_to_mature: 1,
      carbon_per_year_kg: 0.02,
    },
    {
      species: 'fritillaria_meleagris',
      common_name: 'Fritillaire pintade (Fritillaria meleagris)',
      mature_height_cm: 30,
      mature_canopy_cm: 10,
      growth_rate: 'slow',
      years_to_mature: 1,
      carbon_per_year_kg: 0.03,
    },
    {
      species: 'tulipa_sylvestris',
      common_name: 'Tulipe sauvage (Tulipa sylvestris)',
      mature_height_cm: 40,
      mature_canopy_cm: 15,
      growth_rate: 'medium',
      years_to_mature: 1,
      carbon_per_year_kg: 0.04,
    },
    {
      species: 'allium_ursinum',
      common_name: 'Ail des ours (Allium ursinum)',
      mature_height_cm: 30,
      mature_canopy_cm: 20,
      growth_rate: 'medium',
      years_to_mature: 1,
      carbon_per_year_kg: 0.03,
    },
    {
      species: 'muscari_armeniacum',
      common_name: 'Muscari d\'Arménie (Muscari armeniacum)',
      mature_height_cm: 20,
      mature_canopy_cm: 10,
      growth_rate: 'medium',
      years_to_mature: 1,
      carbon_per_year_kg: 0.02,
    },
  ],
};
